databases:
  - name: portasimple_db
    databaseName: portasimple
    user: portasimple_user

services:
  - type: web
    name: portasimple
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn gryst_photo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portasimple_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.9
