databases:
  - name: portasimple_db
    databaseName: portasimple
    user: portasimple_user

services:
  - type: web
    name: portasimple
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gryst_photo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portasimple_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
